trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
        checkLatest: true
      displayName: 'Install Node.js'

    - script: |
        cd client
        npm install
        npm run build
        cd ../api
        npm install
      displayName: 'Install dependencies and build client'

    - script: |
        cd api
        npm start &
        sleep 5
        cd ..
        cd client
        npm run dev &
        sleep 5
      displayName: 'Both Frontend and Backend Running'

    - script: |
        cd client
        npm run test
      displayName: 'Run Selenium tests'

    - script: |
        mkdir -p api/client_build
        cp -R client/build/* api/client_build/
      displayName: 'Copy client build to api folder'

    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)
        cp -R api/* $(Build.ArtifactStagingDirectory)
      displayName: 'Copy build artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish build artifacts'
