trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallAndBuild
  displayName: 'Install Dependencies and Build'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
        checkLatest: true
    
    - script: |
        cd client
        npm install
        npm run build
      displayName: 'Install Client Dependencies and Build Frontend'

    - script: |
        npm install
      displayName: 'Install Backend Dependencies and Build Backend'
    

    - script: |
        npm start &
        sleep 10
        cd client
        npm run dev &
        sleep 10
        npm test
      displayName: 'Run Tests with Both Frontend and Backend Running'

    - task: CopyFiles@2
      inputs:
        Contents: |
          client/dist/**
          api/**
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
